import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "./(landing)/nav-bar";
import Footer from "./Footer";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title:"Ecommerce",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en" data-theme="light">
        <body className={inter.className}>
          <NavBar/>
          {children}
          <Footer/>
      </body>
      </html>
  );
}
